### ISSUE TITLE
Does this work with another setState?

### ISSUE THREAD

**Issue by aocenas** [dai-shi/react-hooks-easy-redux#2]
I did not actually try the code, just looked at the source and this https://github.com/dai-shi/react-hooks-easy-redux/blob/master/src/index.js#L50 part seems like it would prevent any updates that were not triggered by the redux change. Like if I had also local useState which would change, this code would just prevent any updates until also the redux store changed. Is that correct or is there some part I do not get about this approach?

**Comment by dai-shi** [comment]
The argument of `useReduxState` can be used for it.
I just created another example.
https://github.com/dai-shi/react-hooks-easy-redux/blob/master/examples/05_localstate/Counter.tsx#L11

I know it's tricky. I wish we would have a better solution.

**Comment by aocenas** [comment]
Ah right, missed that, thanks for explanation.

**Comment by dai-shi** [comment]
Not at all. Thanks for pointing out. I think the document should be more improved.
