### ISSUE TITLE
state as object

### ISSUE THREAD

**Issue by hamidnoei** [dai-shi/react-hooks-easy-redux#6]
Hi,
I tried to use an object in my state but it seems like there is an issue, I have to dispatch three times to get the updated state in my component.

This is the code: 
```javascript 
const initialState = {
  game: { pin: null }
};

export const reducer = (state = initialState, action) => {
  console.log('state', state);
  switch (action.type) {
    case 'setNewGame':
      return {
        ...state,
        game: {
          ...state.game,
          pin: action.gamePin
        }
      };
    default:
      return state;
  }
};
```

**Comment by dai-shi** [comment]
Hi, the reducer function looks ok.
Could you provide a codesandbox to reproduce the weird behavior?
I'm very interested in the problem. Thanks.

**Comment by hamidnoei** [comment]
Sorry I think it was a bug, I rewrote everything and it's working now, thanks for quick response. Also a `redux-thunk` in examples folder would be great! Thanks!

**Comment by dai-shi** [comment]
Good to hear that. I will create a `thunk` example later.

**Comment by dai-shi** [comment]
Just added `09_thunk`. Hope it helps.

Let me close this issue.

**Comment by hamidnoei** [comment]
Thanks a lot for thunk example!
